## **Por que inglês?? Calma, estarei contigo!!**

O inglês desempenha um papel fundamental no mundo da programação por várias razões:

1. **Padrão da Indústria**: A maioria das documentações, fóruns, tutoriais e recursos relacionados à programação estão em inglês. Isso torna o inglês a língua franca da programação e é essencial para acessar e aproveitar esses recursos.

2. **Comunicação Global**: A programação é frequentemente um esforço colaborativo que envolve desenvolvedores de todo o mundo. O inglês é a língua comum usada para comunicação entre equipes globais de desenvolvimento de software.

3. **Nomenclatura**: Muitos termos técnicos, palavras-chave e bibliotecas em programação são em inglês. Usar esses termos em seu idioma original ajuda a evitar confusões e erros.

4. **Manutenção e Leitura de Código**: Mesmo que você esteja escrevendo código para uso pessoal, outras pessoas podem precisar lê-lo ou mantê-lo. Escrever em inglês torna o código mais acessível e compreensível para um público mais amplo.


### OBS: Se você sentir muita dificuldade, me mande uma mensagem no instagram que eu gero um código desse em português, mas eu considero essencial você tentar! Pode usar o chat gpt, google tradutor e outras ferramentas para te auxiliarem na tradução. Vale tudo!



### NOTEBOOK ADAPTADO DO ORIGINAL: https://www.kaggle.com/code/alexisbcook/titanic-tutorial

# First Steps

So if this is your first time entering a Kaggle competition, regardless of whether you:
- have experience with handling large datasets,
- haven't done much coding,
- are newer to data science, or
- are relatively experienced (but are just unfamiliar with Kaggle's platform),

you're in the right place!

# Part 1: Get started

In this section, you'll learn more about the competition and make your first submission.

## Join the competition!

The first thing to do is to join the competition!  Open a new window with **[the competition page](https://www.kaggle.com/c/titanic)**, and click on the **"Join Competition"** button, if you haven't already.  (_If you see a "Submit Predictions" button instead of a "Join Competition" button, you have already joined the competition, and don't need to do so again._)

![](https://i.imgur.com/07cskyU.png)

This takes you to the rules acceptance page.  You must accept the competition rules in order to participate.  These rules govern how many submissions you can make per day, the maximum team size, and other competition-specific details.   Then, click on **"I Understand and Accept"** to indicate that you will abide by the competition rules.

## The challenge

The competition is simple: we want you to use the Titanic passenger data (name, age, price of ticket, etc) to try to predict who will survive and who will die.

## The data

To take a look at the competition data, click on the **<a href="https://www.kaggle.com/c/titanic/data" target="_blank" rel="noopener noreferrer"><b>Data tab</b></a>** at the top of the competition page.  Then, scroll down to find the list of files.  
There are three files in the data: (1) **train.csv**, (2) **test.csv**, and (3) **gender_submission.csv**.

### (1) train.csv

**train.csv** contains the details of a subset of the passengers on board (891 passengers, to be exact -- where each passenger gets a different row in the table).  To investigate this data, click on the name of the file on the left of the screen.  Once you've done this, you can view all of the data in the window.  

![](https://i.imgur.com/cYsdt0n.png)

The values in the second column (**"Survived"**) can be used to determine whether each passenger survived or not:
- if it's a "1", the passenger survived.
- if it's a "0", the passenger died.

For instance, the first passenger listed in **train.csv** is Mr. Owen Harris Braund.  He was 22 years old when he died on the Titanic.

### (2) test.csv

Using the patterns you find in **train.csv**, you have to predict whether the other 418 passengers on board (in **test.csv**) survived.  

Click on **test.csv** (on the left of the screen) to examine its contents.  Note that **test.csv** does not have a **"Survived"** column - this information is hidden from you, and how well you do at predicting these hidden values will determine how highly you score in the competition!

### (3) gender_submission.csv

The **gender_submission.csv** file is provided as an example that shows how you should structure your predictions.  It predicts that all female passengers survived, and all male passengers died.  Your hypotheses regarding survival will probably be different, which will lead to a different submission file.  But, just like this file, your submission should have:
- a **"PassengerId"** column containing the IDs of each passenger from **test.csv**.
- a **"Survived"** column (that you will create!) with a "1" for the rows where you think the passenger survived, and a "0" where you predict that the passenger died.

# Part 2: Your coding environment

In this section, you'll train your own machine learning model to improve your predictions.  _If you've never written code before or don't have any experience with machine learning, don't worry!  We don't assume any prior experience in this notebook._

In [34]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

This shows us where the competition data is stored, so that we can load the files into the notebook.  We'll do that next.

## Load the data

The second code cell in your notebook now appears below the three lines of output with the file locations.

In [37]:
train_data = pd.read_csv("train.csv")
train_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Your code should return the output above, which corresponds to the first five rows of the table in **train.csv**.  It's very important that you see this output **in your notebook** before proceeding!

The code that you've just written is in the Python programming language. It uses a Python "module" called **pandas** (abbreviated as `pd`) to load the table from the **train.csv** file into the notebook. To do this, we needed to plug in the location of the file (which we saw was `/train.csv`).  
> If you're not already familiar with Python (and pandas), the code shouldn't make sense to you -- but don't worry!  The point of this tutorial is to (quickly!) make your first submission to the competition.  At the end of the tutorial, we suggest resources to continue your learning.

In [39]:
test_data = pd.read_csv("test.csv")
test_data

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

As before, make sure that you see the output above in your notebook before continuing.  

Once all of the code runs successfully, all of the data (in **train.csv** and **test.csv**) is loaded in the notebook.  (_The code above shows only the first 5 rows of each table, but all of the data is there -- all 891 rows of **train.csv** and all 418 rows of **test.csv**!_)

# Part 3: Your first submission

Remember our goal: we want to find patterns in **train.csv** that help us predict whether the passengers in **test.csv** survived.

It might initially feel overwhelming to look for patterns, when there's so much data to sort through.  So, we'll start simple.

## Explore a pattern

Remember that the sample submission file in **gender_submission.csv** assumes that all female passengers survived (and all male passengers died).  

Is this a reasonable first guess?  We'll check if this pattern holds true in the data (in **train.csv**).

Copy the code below into a new code cell.  Then, run the cell.

In [40]:
women = train_data.loc[train_data.Sex == 'female']["Survived"]

In [41]:
women

1      1
2      1
3      1
8      1
9      1
      ..
880    1
882    0
885    0
887    1
888    0
Name: Survived, Length: 314, dtype: int64

In [43]:
rate_women = sum(women)/len(women)

In [44]:
rate_women

0.7420382165605095

In [45]:
print("% of women who survived:", rate_women)

% of women who survived: 0.7420382165605095

Before moving on, make sure that your code returns the output above.  The code above calculates the percentage of female passengers (in **train.csv**) who survived.

Then, run the code below in another code cell:

In [46]:
men = train_data.loc[train_data.Sex == 'male']["Survived"]
rate_men = sum(men)/len(men)

print("% of men who survived:", rate_men)

% of men who survived: 0.18890814558058924

The code above calculates the percentage of male passengers (in **train.csv**) who survived.

From this you can see that almost 75% of the women on board survived, whereas only 19% of the men lived to tell about it. Since gender seems to be such a strong indicator of survival, the submission file in **gender_submission.csv** is not a bad first guess!

But at the end of the day, this gender-based submission bases its predictions on only a single column.  As you can imagine, by considering multiple columns, we can discover more complex patterns that can potentially yield better-informed predictions.  Since it is quite difficult to consider several columns at once (or, it would take a long time to consider all possible patterns in many different columns simultaneously), we'll use machine learning to automate this for us.

## Your first machine learning model

We'll build what's known as a **random forest model**.  This model is constructed of several "trees" (there are three trees in the picture below, but we'll construct 100!) that will individually consider each passenger's data and vote on whether the individual survived.  Then, the random forest model makes a democratic decision: the outcome with the most votes wins!

![](https://i.imgur.com/AC9Bq63.png)

The code cell below looks for patterns in four different columns (**"Pclass"**, **"Sex"**, **"SibSp"**, and **"Parch"**) of the data.  It constructs the trees in the random forest model based on patterns in the **train.csv** file, before generating predictions for the passengers in **test.csv**.  The code also saves these new predictions in a CSV file **submission.csv**.

In [47]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\python312\lib\site-packages (1.4.0)
Requirement already satisfied: numpy<2.0,>=1.19.5 in c:\python312\lib\site-packages (from scikit-learn) (1.26.2)
Requirement already satisfied: scipy>=1.6.0 in c:\python312\lib\site-packages (from scikit-learn) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in c:\python312\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\python312\lib\site-packages (from scikit-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

In [48]:
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass", "Sex", "SibSp", "Parch"]

In [49]:
train_data[features]

     Pclass     Sex  SibSp  Parch
0         3    male      1      0
1         1  female      1      0
2         3  female      0      0
3         1  female      1      0
4         3    male      0      0
..      ...     ...    ...    ...
886       2    male      0      0
887       1  female      0      0
888       3  female      1      2
889       1    male      0      0
890       3    male      0      0

[891 rows x 4 columns]

In [50]:
pd.get_dummies(train_data[features])

     Pclass  SibSp  Parch  Sex_female  Sex_male
0         3      1      0       False      True
1         1      1      0        True     False
2         3      0      0        True     False
3         1      1      0        True     False
4         3      0      0       False      True
..      ...    ...    ...         ...       ...
886       2      0      0       False      True
887       1      0      0        True     False
888       3      1      2        True     False
889       1      0      0       False      True
890       3      0      0       False      True

[891 rows x 5 columns]

In [58]:
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=20, max_depth=10, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)

In [54]:
predictions

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
      dtype=int64)

In [55]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

In [56]:
len(predictions)

418

## Model Evaluation Methods

Evaluation model methods are essential in data science as they serve to assess the performance of machine learning models, allowing data scientists to select the best model, fine-tune hyperparameters, address overfitting and underfitting, and provide feedback to stakeholders. These metrics help manage risk, enable continual improvement, offer interpretability, and ensure accountability and compliance in regulated industries, ultimately ensuring that data-driven decisions are accurate, reliable, and aligned with project objectives.

1. **Accuracy:** Measures the proportion of correct predictions in relation to the total number of predictions. It's a general performance metric, but may not be suitable in cases of class imbalance.

2. **Precision:** Measures the proportion of correct positive predictions in relation to the total number of positive predictions. It's useful when the cost of false positives is high, such as in spam detection.

3. **Recall (or Sensitivity):** Measures the proportion of actual positive instances that were correctly identified by the model. It's useful when the cost of false negatives is high, such as in disease detection.

4. **F1-Score:** It's the harmonic mean of precision and recall. It helps balance the precision and recall metrics and is useful when both are important.

5. **AUC-ROC (Area Under the ROC Curve):** Evaluates the performance of a binary classification model by plotting the true positive rate against the false positive rate at different thresholds. The higher the AUC-ROC, the better the model discriminates between classes.

6. **ROC Curve:** Graphically represents the true positive rate versus the false positive rate at different thresholds. The AUC-ROC is the area under this curve.

7. **AUC-PR (Area Under the Precision-Recall Curve):** Evaluates the model's performance in terms of precision and recall, particularly useful in class-imbalanced problems. It measures the area under the precision-recall curve.

8. **Precision-Recall Curve:** Graphically represents precision versus recall at different thresholds. The AUC-PR is the area under this curve.

9. **Confusion Matrix:** A table that shows the number of true positives (TP), true negatives (TN), false positives (FP), and false negatives (FN) of the model. It helps understand performance in detail and calculate other metrics.

Each metric serves a specific purpose and is used based on the needs and characteristics of the classification problem. The choice of the appropriate metric depends on the context and the implications of false positives and false negatives in your scenario.

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, average_precision_score, jaccard_score

# Suponha que você tenha suas previsões (y_pred) e os rótulos reais (y_true)
y_true = pd.read_csv("gender_submission.csv")
y_true = y_true['Survived']
y_pred = predictions

# Matriz de Confusão
confusion = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:\n", confusion)

# Acurácia
accuracy = accuracy_score(y_true, y_pred)
print("Accuracy:", accuracy)

# Precisão
precision = precision_score(y_true, y_pred)
print("Precision:", precision)

# Revocação
recall = recall_score(y_true, y_pred)
print("Recall:", recall)

# F1-Score
f1 = f1_score(y_true, y_pred)
print("F1-Score:", f1)

# Índice de Jaccard
jaccard = jaccard_score(y_true, y_pred)
print("Jaccard Index:", jaccard)

Confusion Matrix:
 [[254  12]
 [ 17 135]]
Accuracy: 0.930622009569378
Precision: 0.9183673469387755
Recall: 0.8881578947368421
F1-Score: 0.903010033444816
Jaccard Index: 0.823170731707317

## Submission

Make sure that your notebook outputs the same message above (`Your submission was successfully saved!`) before moving on.
> Again, don't worry if this code doesn't make sense to you!  For now, we'll focus on how to generate and submit predictions.

Once you're ready, click on the **"Save Version"** button in the top right corner of your notebook.  This will generate a pop-up window.  
- Ensure that the **"Save and Run All"** option is selected, and then click on the **"Save"** button.
- This generates a window in the bottom left corner of the notebook.  After it has finished running, click on the number to the right of the **"Save Version"** button.  This pulls up a list of versions on the right of the screen.  Click on the ellipsis **(...)** to the right of the most recent version, and select **Open in Viewer**.  
- Click on the **Data** tab on the top of the screen.  Then, click on the **"Submit"** button to submit your results.

![](https://i.imgur.com/1ocaUl4.png)

Congratulations for making your first submission to a Kaggle competition!  Within ten minutes, you should receive a message providing your spot on the leaderboard.  Great work!

# Part 4: Learn more!

If you're interested in learning more about Machine Learning, I strongly suggest you to subscribe to (3-hour) **[Intro to Machine Learning](https://www.kaggle.com/learn/intro-to-machine-learning)** course, which will help you fully understand all of the code that we've presented here.  You'll also know enough to generate even better predictions!